DROP ALL OBJECTS;

create table if not exists activitylog ( 
  id bigint NOT NULL AUTO_INCREMENT,
  process varchar(200) NOT NULL,
  processId varchar(200) NOT NULL,
  summary varchar(200) NULL,
  result  varchar(50)  NULL,
  error  varchar(max) NULL,
  clientip varchar(100) NULL,
  createdBy bigint,
  createdDate timestamp NOT NULL,
  lastModifiedBy bigint,
  lastModifiedDate timestamp NOT NULL,
  lastUpdatedByprocessId varchar(200) NULL,
  isdeleted bigint NOT NULL default 0,
  version bigint NOT NULL,
  PRIMARY KEY (Id)
);

create table if not exists activitylogDetails ( 
  id bigint NOT NULL AUTO_INCREMENT,
  entity varchar(100) NOT NULL,
  entityid bigint NOT NULL,
  entityrevision bigint NOT NULL,
  processid varchar(200) NULL,
  createdBy bigint,
  createdDate timestamp NOT NULL,
  lastModifiedBy bigint,
  lastModifiedDate timestamp NOT NULL,
  lastUpdatedByprocessId varchar(200) NULL,
  isdeleted bigint NOT NULL default 0,
  version bigint NOT NULL,
  PRIMARY KEY (Id)
);

create table if not exists persistent_logins ( 
  username varchar_ignorecase(100) not null, 
  series varchar(64) primary key, 
  token varchar(64) not null, 
  last_used timestamp not null
);

CREATE TABLE ARTICLES (
  id bigint(5) NOT NULL AUTO_INCREMENT,
  title varchar(200) NOT NULL,
  category varchar(100) NULL,
  summary varchar(200) NULL,
  author varchar(100) NULL,
  createdBy bigint,
  createdDate timestamp NOT NULL,
  lastModifiedBy bigint,
  lastModifiedDate timestamp NOT NULL,
  lastUpdatedByprocessId varchar(200) NULL,
  isdeleted bigint NOT NULL default 0,
  version bigint NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE ARTICLES_AUD (
  id bigint(5) NOT NULL AUTO_INCREMENT,
  title varchar(200),
  title_mod boolean,
  category varchar(100),
  category_mod boolean,
  summary varchar(200),
  summary_mod boolean,
  author varchar(100),
  author_mod boolean,
  createdBy bigint,
  createdBy_mod boolean,
  createdDate timestamp,
  createdDate_mod boolean,
  lastModifiedBy bigint,
  lastModifiedBy_mod boolean,
  lastModifiedDate timestamp,
  lastModifiedDate_mod boolean,
  version bigint,
  lastUpdatedByprocessId varchar(200),
  lastUpdatedByprocessId_mod boolean,
  isdeleted bigint,
  isdeleted_mod boolean,
  REV INTEGER NOT NULL,
  REVTYPE INTEGER NOT NULL,
  PRIMARY KEY (Id, REV)
);

CREATE TABLE REVINFO (
    REV INTEGER GENERATED BY DEFAULT AS IDENTITY,
    REVTSTMP BIGINT,
    PRIMARY KEY (REV)
);

create table if not exists OAUTH_USERS ( 
  id bigint NOT NULL AUTO_INCREMENT,
  O_AUTH_ID varchar(250) NOT NULL UNIQUE,
  global_User_Id bigint not null,
  PRIMARY KEY (id)
);
 
create table if not exists GLOBAL_USERS ( 
  id bigint NOT NULL AUTO_INCREMENT,
  created datetime not null,
  PRIMARY KEY (id)
);

create table if not exists users(
    id bigint NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) not null,
    password VARCHAR(100) not null,
    passwordExpirationDate timestamp not null,
    enabled boolean not null,
    createdBy bigint,
    createdDate timestamp NOT NULL,
    lastModifiedBy bigint,
    lastModifiedDate timestamp NOT NULL,
    lastUpdatedByprocessId varchar(200) NULL,
    isdeleted bigint NOT NULL default 0,
    version bigint NOT NULL,
    primary key (id)
);

create table if not exists users_aud (
  id bigint NOT NULL,
  username VARCHAR(50) not null,
  username_mod boolean,
  password VARCHAR(100) not null,
  password_mod boolean,
  passwordExpirationDate timestamp not null,
  passwordExpirationDate_mod boolean,
  enabled boolean not null,
  enabled_mod boolean,
  createdBy bigint,
  createdBy_mod boolean,
  createdDate timestamp,
  createdDate_mod boolean,
  lastModifiedBy bigint,
  lastModifiedBy_mod boolean,
  lastModifiedDate timestamp,
  lastModifiedDate_mod boolean,
  version bigint,
  lastUpdatedByprocessId varchar(200),
  lastUpdatedByprocessId_mod boolean,
  isdeleted bigint,
  isdeleted_mod boolean,
  REV INTEGER NOT NULL,
  REVTYPE INTEGER NOT NULL,
  PRIMARY KEY (Id, REV)
);

create table if not exists failedLoginAttempts(
    id bigint NOT NULL,
    username VARCHAR(50) not null,
    timestamp timestamp not null,
    primary key (id)
);

create table if not exists authorities (
    username VARCHAR(50) not null,
    authority VARCHAR(50) not null,
    constraint fk_authorities_users foreign key(username) references users(username)
);
create unique index ix_auth_username on authorities (username,authority);

create table if not exists persistent_logins ( 
  username varchar_ignorecase(100) not null, 
  series varchar(64) primary key, 
  token varchar(64) not null, 
  last_used timestamp not null 
);

create table if not exists roles ( 
  id bigint not null AUTO_INCREMENT primary key, 
  name varchar(64) ,
  createdBy bigint,
  createdDate timestamp NOT NULL,
  lastModifiedBy bigint,
  lastModifiedDate timestamp NOT NULL,
  lastUpdatedByprocessId varchar(200) NULL,
  isdeleted bigint NOT NULL default 0,
  version bigint NOT NULL
);

create table if not exists user_role ( 
  user_id bigint not null, 
  role_id bigint not null,
  constraint fk_user_role_users foreign key(user_id) references users(id),
  constraint fk_user_role_roles foreign key(role_id) references roles(id)
);

create table if not exists privilege ( 
  id bigint not null primary key,
  name varchar(120) not null
);

create table if not exists roles_privileges ( 
  role_id bigint not null,
  privilege_id bigint not null, 
  constraint fk_user_role_privilege foreign key(privilege_id) references privilege(id),
  constraint fk_user_role_role foreign key(role_id) references roles(id)
);

 CREATE SEQUENCE if not exists privileges_sequence
  START WITH 1
  INCREMENT BY 1;

 CREATE SEQUENCE if not exists roles_sequence
  START WITH 1
  INCREMENT BY 1;

 CREATE SEQUENCE if not exists activitylog_sequence
  START WITH 1
  INCREMENT BY 1;
  
 CREATE SEQUENCE if not exists activitylogDetails_sequence
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE if not exists articles_sequence
  START WITH 17
  INCREMENT BY 1;

CREATE SEQUENCE if not exists users_sequence
  START WITH 3
  INCREMENT BY 1;
  
  CREATE SEQUENCE if not exists failedLoginAttempts_sequence
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE if not exists oauthusers_sequence
  START WITH 1
  INCREMENT BY 1;
  
  CREATE SEQUENCE if not exists globalusers_sequence
  START WITH 2
  INCREMENT BY 1;